"""Launches Castro runs as detached background processes -- the same
setsid/nohup pattern used by hand throughout this session -- and exposes
a pure, non-blocking way to read progress from the log file. Nothing
here ever waits on a Castro process; QTimer-driven polling in the UI
layer calls `read_progress()` periodically.
"""

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from core.star_builder import half_shift_domain

WD_BRAITHWAITE_DIR = Path("/home/rafael/wd-magnetizada/castro/Exec/science/wd_braithwaite")
EXECUTABLE = WD_BRAITHWAITE_DIR / "Castro3d.gnu.MPI.ex"

# Fixed/automatic configuration inherited from this session's validated
# runs -- never exposed to the user (see main.py's module docstring).
BOX_HALF_WIDTH_CM = 4.9e8
DAMPING_TIMESCALE_IN_TDYN = 0.2
DAMPING_END_TIME_IN_TDYN = 5.0
DAMPING_RAMP_IN_TDYN = 1.0
SMALL_DENS = 1.0e4
SMALL_TEMP = 1.0e3

_INPUTS_TEMPLATE = """\
# Generated by braithwaite_app/core/run_launcher.py -- do not hand-edit;
# regenerate via the app if parameters need to change.
max_step = {max_step}
stop_time = {stop_time}

geometry.is_periodic =  0    0    0
geometry.coord_sys   =  0
geometry.prob_lo     = {prob_lo:.10e} {prob_lo:.10e} {prob_lo:.10e}
geometry.prob_hi     = {prob_hi:.10e} {prob_hi:.10e} {prob_hi:.10e}
amr.n_cell           = {n_cell} {n_cell} {n_cell}

castro.lo_bc       =  2   2   2
castro.hi_bc       =  2   2   2

castro.do_hydro = 1
castro.do_react = 0
castro.ppm_type = 0
castro.use_flattening = 0

castro.do_grav = 1
gravity.gravity_type = MonopoleGrav
gravity.drdxfac = 2

castro.cfl            = 0.5
castro.init_shrink    = 0.01
castro.change_max     = 1.1

castro.sum_interval   = 1
castro.v              = 1
amr.v                 = 1

amr.max_level       = 0
amr.ref_ratio       = 2 2 2 2
amr.regrid_int      = 2
amr.blocking_factor = 8
amr.max_grid_size   = {max_grid_size}

amr.check_file      = {check_file}
amr.check_int       = {check_int}
amr.plot_file       = {plot_file}
amr.plot_int        = {plot_int}
amr.derive_plot_vars = density x_velocity y_velocity z_velocity eden Temp pressure B_x B_y B_z Div_B emag_density etor_density

castro.small_dens = {small_dens}
castro.small_temp = {small_temp}

castro.do_sponge = 1
castro.sponge_upper_density = 1.0e5
castro.sponge_lower_density = 1.0e4
castro.sponge_timescale     = 1.0e-4

castro.add_ext_src = 1

problem.model_name = "model.dat"
problem.rng_seed = {rng_seed}
problem.E_mag_over_W_target = {e_mag_over_w}
problem.n_modes = 10
problem.dominant_scale_over_R = 0.3
problem.mode_scale_band_factor = 3.0
problem.field_cutoff_frac = 0.8
problem.envelope_transition_frac = 0.2
problem.surface_density_frac = 2.0e-4
problem.damping_timescale_in_tdyn = {damping_timescale_in_tdyn}
problem.damping_end_time_in_tdyn = {damping_end_time_in_tdyn}
problem.damping_ramp_in_tdyn = {damping_ramp_in_tdyn}
"""


@dataclass
class RunSpec:
    run_id: str                  # unique name -- used for plot/check prefixes and log filename
    n_cell: int
    rng_seed: int
    e_mag_over_w: float
    stop_time_s: float
    max_step: int = 2000
    plot_int: int = 10
    check_int: int = 200
    np: int = 1


def render_inputs(spec: RunSpec) -> str:
    prob_lo, prob_hi = half_shift_domain(spec.n_cell, BOX_HALF_WIDTH_CM)
    max_grid_size = 32 if spec.n_cell == 64 else 64  # multi-box decomposition for -np>1
    return _INPUTS_TEMPLATE.format(
        max_step=spec.max_step,
        stop_time=spec.stop_time_s,
        prob_lo=prob_lo,
        prob_hi=prob_hi,
        n_cell=spec.n_cell,
        max_grid_size=max_grid_size,
        check_file=f"chk_{spec.run_id}",
        check_int=spec.check_int,
        plot_file=f"plt_{spec.run_id}",
        plot_int=spec.plot_int,
        small_dens=SMALL_DENS,
        small_temp=SMALL_TEMP,
        rng_seed=spec.rng_seed,
        e_mag_over_w=spec.e_mag_over_w,
        damping_timescale_in_tdyn=DAMPING_TIMESCALE_IN_TDYN,
        damping_end_time_in_tdyn=DAMPING_END_TIME_IN_TDYN,
        damping_ramp_in_tdyn=DAMPING_RAMP_IN_TDYN,
    )


def launch(spec: RunSpec, run_dir: Path = WD_BRAITHWAITE_DIR, log_dir: Path = None) -> Path:
    """Writes the inputs file and launches Castro as a fully detached
    background process (setsid session leader, stdin from /dev/null,
    stdout/stderr to a fixed log file) -- survives this Python process
    exiting, exactly like every run launched by hand this session.
    Returns the log file path; launch itself returns immediately.
    """
    log_dir = log_dir or run_dir
    inputs_path = run_dir / f"inputs.{spec.run_id}"
    inputs_path.write_text(render_inputs(spec))

    log_path = log_dir / f"run_{spec.run_id}.log"

    cmd = ["mpirun", "-np", str(spec.np), str(EXECUTABLE), inputs_path.name]
    with open(log_path, "wb") as logf:
        subprocess.Popen(
            cmd,
            cwd=str(run_dir),
            stdout=logf,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            start_new_session=True,  # setsid equivalent -- detaches from this process's session
        )
    return log_path


@dataclass
class Progress:
    t_dyn_s: float | None = None
    w_abs_erg: float | None = None
    t_s: float = 0.0
    t_ttdyn: float = 0.0
    rho_c: float | None = None
    status: str = "launching"  # launching -> running -> ended | error
    error_text: str | None = None


_T_DYN_RE = re.compile(r"t_dyn = ([\d.eE+-]+) s")
_W_ABS_RE = re.compile(r"\|W\| = ([\d.eE+-]+) erg")
_TIME_RHO_RE = re.compile(r"TIME=\s*([\d.eE+-]+) MAXIMUM DENSITY\s*=\s*([\d.eE+-]+)")
_ERROR_MARKERS = ("amrex::Abort", "SIGABRT", "SIGSEGV", "No space left on device")


def read_progress(log_path: Path, run_id: str) -> Progress:
    """Pure, non-blocking read of whatever the log has so far. Safe to
    call repeatedly from a QTimer -- never waits on the process."""
    p = Progress()
    if not log_path.exists():
        return p

    text = log_path.read_text(errors="replace")
    if not text:
        return p

    p.status = "running"

    m = _T_DYN_RE.search(text)
    if m:
        p.t_dyn_s = float(m.group(1))

    m = _W_ABS_RE.search(text)
    if m:
        p.w_abs_erg = float(m.group(1))

    last_match = None
    for m in _TIME_RHO_RE.finditer(text):
        last_match = m
    if last_match:
        p.t_s = float(last_match.group(1))
        p.rho_c = float(last_match.group(2))
        if p.t_dyn_s:
            p.t_ttdyn = p.t_s / p.t_dyn_s

    for marker in _ERROR_MARKERS:
        if marker in text:
            p.status = "error"
            idx = text.rfind(marker)
            p.error_text = text[max(0, idx - 200):idx + 200]
            break

    if not is_process_alive(run_id) and p.status == "running":
        p.status = "ended"

    return p


def is_process_alive(run_id: str) -> bool:
    result = subprocess.run(
        ["pgrep", "-f", f"Castro3d.gnu.MPI.ex inputs.{run_id}"],
        capture_output=True, text=True,
    )
    return bool(result.stdout.strip())
